[tool.poetry]
name = "telegram-bot-massage"
version = "0.1.0"
description = ""
authors = ["anwer1230"]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.111.1"
uvicorn = {extras = ["standard"], version = "0.23.2"}
telethon = "1.28.0"
python-dotenv = "1.0.0"
jinja2 = "3.1.4"
